---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-video-pv
spec:
  storageClassName: video
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.5
    path: /volume1/video
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: video
  resources:
    requests:
      storage: 1Mi
