---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dash-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 128Mi
