---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - descheduler
  - intel-gpu-plugin
  - metrics-server
  - nfs-subdir-external-provisioner
  - node-feature-discovery
  - node-problem-detector
  - reloader
