# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: br0testbot-token
    namespace: bots
    type: Opaque
data:
    TELEGRAM_API_KEY: ENC[AES256_GCM,data:b6IfgYlXkAdpawc4v7iufMHDXiwWKIKkg+ED3ZX0d3A76l5wkIbHcZFnq1aSvA==,iv:80y4dppmKJFwHeJ50SjxkEFbX8AZWoDbCfzD06QbwUA=,tag:p3DZjTtNpdNdd/V5DMUVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3clQzY0E1UnZWV1VhMG5P
            cytLbUd6RjJla2VuSUF4akc2aVc0L1k1cVU0ClJVRlpWTVFyUkhtZ1p4cFU4YmRK
            bFdWMStkL3llQVUydlBsOHZ1b1YyNXcKLS0tIEZWRjE3SEw4UHRrcE1QRklaOFBY
            bE5SbmhvWmFOY2N4MDVBcVM4YklkS00Ku+suPCdBK5dJgKxm8E7et/PtHxlaiF7u
            wuaLHa+7i8IpuO0UqxHIET1VAfeNoODQDnFC3fZ0CP2V54sCtQpwuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T20:32:31Z"
    mac: ENC[AES256_GCM,data:AIoJTo0YzSGAYE/S77SlwxzffZaqeuOEVYHvqAwPc3EwShKb/LDthibzyzNecoh9xXWdJQKZPa5baTN8rK8QSESSlYKsY3pTlsPpiKRZL7Eu9GD9PmLOeB+aW9955kxhNaxiJlc+ZffCaYt/WhSb6ufrn4nClt8fnrBE/9yHmJU=,iv:5eWS+gJ2gRe0uSch05O7pw+0NI3dxydGySDx5HewktA=,tag:RJBcMsYs22nx3Ybim3L3ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
