# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: br0testbot-token
    namespace: bots
stringData:
    TELEGRAM_API_KEY: ENC[AES256_GCM,data:E1lLM7NnNRqAz/u1nqnwkY/SHd2erq7i3Ob7Rhc5E4S9Pjf4SX5LCG4S4M51cw==,iv:2P7k+dzqv+bfPtCr7ClSan4zKhR//9C4B7MRuUqSlNY=,tag:FtGd6qW3l0vPtwFgy6I4uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3clQzY0E1UnZWV1VhMG5P
            cytLbUd6RjJla2VuSUF4akc2aVc0L1k1cVU0ClJVRlpWTVFyUkhtZ1p4cFU4YmRK
            bFdWMStkL3llQVUydlBsOHZ1b1YyNXcKLS0tIEZWRjE3SEw4UHRrcE1QRklaOFBY
            bE5SbmhvWmFOY2N4MDVBcVM4YklkS00Ku+suPCdBK5dJgKxm8E7et/PtHxlaiF7u
            wuaLHa+7i8IpuO0UqxHIET1VAfeNoODQDnFC3fZ0CP2V54sCtQpwuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T19:48:11Z"
    mac: ENC[AES256_GCM,data:vOz54Tdjdx0U42/d8W+62Si2XBA1ByKaRwJgzYMqh5P7tF8ZgOYr4PQkHjks+jfseMcXDgqtYenNwGrrUL1RxzqeWOVtcVqm0X5CWFBB8goLvspH+qmGb538hWJytdh9JJMclOYU0RIrLDrO+sQq8rtyuddVMjdRY3787X+E8Gk=,iv:iZLjCEGLgCOkOYkLj9N2ifhXT1YVFnG3NjHKjeCJL7Q=,tag:rsIWqCx5lcaMxvhfjAjXQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
