# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    token: ENC[AES256_GCM,data:2KAeW0YF2Dw0P9zJoESLXM8TSNILhitf66KxqMi1hIRpkHNWWK3OmA==,iv:6ToeuFsbT6OJbyjGQPuGc0lke2kSOZ8RLYMYUbrQuhU=,tag:izoTGM7ifKPGPB+b8Xi9zg==,type:str]
    email: ENC[AES256_GCM,data:Rx4RwAUHBEMYd0kFODYyMQ==,iv:+sll1benoQhjMSHAFx2Lvct1RXq+Gg2qkxJ7+If9d4I=,tag:mTiiy7XhwlBBqDOkm009EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc2cyZjk4alJxR2twZGRK
            Nnp6TTdMTW9KUjBjSFRyRU1VWUh5cDl3U1VrCjhKV1g1WmdUZVBFMWM4MUcrVWNY
            bHphUTBiMFlvYVhlbklUWHVHNG1rVEkKLS0tIDlzcWdhVjBPQzlYTDVjUWg4YUtH
            TXA4L250TUtFYVhLcEhEc3BocHd5WmcKP/XlAdXCPAyxjakZvlMXVc71I88kJzET
            q0LHqylyKZqWVCJrOzHG4qSM4HZRaNqsUrCHIFLj7ktZkoUoLT29IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-11T18:09:17Z"
    mac: ENC[AES256_GCM,data:57b+Us1n9ADZnglrOMeq5Dglj2kNoky1gdDi4OL2PH7i29jMWwviwjMfeoxoVMuBiFKOzP3pfetkZWiq9pzpyWpRxF+iBvbrO6G/tGVJHwSqrv8CKsxaoPqGN/Bj+B+7EQkJNaZlbb9JcqByMDk+/2k7hqraUexFuwkFBcoY7xc=,iv:rWIW7L9Icmh5A+7w1kGd+rtRu39v3Wh0SLQ760pVFo8=,tag:Dub7KlfU5c9gkfpA4/DnHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
