---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "Europe/Berlin"
      PLEX_CLAIM: "${SECRET_PLEX_CLAIM}"
    podSecurityContext:
      supplementalGroups:
      - 44
      - 109
      - 100
    service:
      main:
        # -- Enables or disables the service
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${LB_PLEX_IP}"
        externalTrafficPolicy: Local
        port:
          port: 32400
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      shared:
        enabled: true
        type: emptyDir
        mountPath: /tmp
        medium: Memory
      video:
        enabled: true
        existingClaim: nfs-video-pvc
        mountPath: /video
        readOnly: true
      music:
        enabled: true
        existingClaim: nfs-music-pvc
        mountPath: /music
        readOnly: true                
    nodeSelector:
        feature.node.kubernetes.io/custom-intel-gpu: 'true'
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1000m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 8192Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
#    addons:
#      promtail:
#        enabled: false
#        image:
#          repository: grafana/promtail
#          tag: 2.2.1
#        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
#        logs:
#        - name: promtail/plex
#          path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
#        - name: promtail/plex/plugins
#          path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
#        volumeMounts:
#        - name: config
#          mountPath: /config
#          readOnly: true
#        securityContext:
#          runAsUser: 0
#
