---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.2.40-192.168.2.50
  METALLB_TRAEFIK_ADDR: 192.168.2.40
  METALLB_TRAEFIK_INT_ADDR: 192.168.2.41
  NFS_SERVER: 192.168.2.5
  NFS_PATH: /volume1/k8s-csi-dev
