# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uat0xY188iYc,iv:9wO2HX2R+fRliKUPz6qEX2CuU9tYBsooWP134Abo4eg=,tag:zfVD4JQSuDCHLHfO3NYDIw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zCpgCznR0lFvbnqIvHhVqg==,iv:fJ9m9VAR19X7T4y2CmkKXjH4S+jVaxVMcqLbetGOOsc=,tag:hNG+1lp1Pp8hcoVGCz1mHQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Xy4+RY9/LkTbPN4eFn315YpkwDUTTB+FHfLUDpA0KpU=,iv:dbWGHEPveyMY1IPjMJ0gQ29td+Fv+eZaNBL00fYGQ9s=,tag:oR0+BP/bQOFJONw6v5lreA==,type:str]
    SECRET_GRAFANA_OAUTH_ID: ENC[AES256_GCM,data:mDBnbZ+2PRSOEgAy/OL2zOENJtk=,iv:l6V9ECvY7HsUMr30wzTjHtYDrzOPUN31DUK0uGPFdls=,tag:WanQYeW3znanPqYo6qVt1A==,type:str]
    SECRET_GRAFANA_OAUTH_SECRET: ENC[AES256_GCM,data:nIbyPGsDSz6Jws1X5UWmvOkHNqiJEc0CrUzwW1yjjbm+Cw3zz2QQTA==,iv:vWCFjwyVpqq2mh9q58WjAgquEp/b3x5uuZhdaJrVies=,tag:wWE10AJNDIo/Ghy1GY+RRA==,type:str]
    SECRET_GRAFANA_OAUTH_ORGANISATIONS: ENC[AES256_GCM,data:sptdx3fukdWp,iv:smfAk5Xsmb90mTUlKmlz+3SV1nKv3PoVrBN7IApkUpw=,tag:rtPgoQs7XGGCVFMAWiSBdQ==,type:str]
    SECRET_GITHUB_TOKEN: ENC[AES256_GCM,data:5R5dfKJ+/NvVDvKUWrmNXwoafnyyqq86wDiyHLYYT5GMvdFx3L93ZA==,iv:elqo4tsIZAdXflokWlsyLQeXv3HKHfciTiucRyAYjec=,tag:WGlKPfw7KgdLv+Piy3XpGQ==,type:str]
    SECRET_UNIFI_USER: ENC[AES256_GCM,data:cX8kb4dTV4+9Gkzy,iv:iHTqc9wZGQ9/tv+gAaCO60nbBvEx4H9TANU6j/eTK9k=,tag:42J2zvKzuiAUI8XrcyPa4w==,type:str]
    SECRET_UNIFI_PASSWORD: ENC[AES256_GCM,data:mtcyilCXez3A+pcJ0zRZuYk=,iv:kn7NE9A3ShmPpPl+cN04QyzfA4b9LuQIuo+d+Qanqb8=,tag:NPSKDIBHof4SbJQUGu94OA==,type:str]
    SECRET_UNIFI_HOST: ENC[AES256_GCM,data:yAnaC5Hvv/oik+fNizeOD6dDeFjPiAw=,iv:TUebWZg59cHn4RCY+C3LVqhR+OHDss+yggtP+9urc7c=,tag:CU97bkMR+Y4P0dVrYVQBfQ==,type:str]
    SECRET_BOT_TOKEN: ENC[AES256_GCM,data:lHQs5ud9QiJGjfFXjMccdw/A9PlL2zDCKR6H7xfdKh4bAylrbT6Kxh07j9EBEg==,iv:XSUz8J8na2P2+QfbnurexOOXIh+vEj8MEB7+YAFmXWo=,tag:oHMmPL/TlHC6v6b6fD+61w==,type:str]
    SECRET_BR0TESTBOT_TOKEN: ENC[AES256_GCM,data:HfnegOFQSaZr5eHZGlRIQZuSW6BuIWp0OjYs48iriEikie0SvgKTii9GdC9rIw==,iv:iBS12tSjf7E9guDEFDvTF/P73awkSHUmZo8BWVrTmWA=,tag:7WPT20px+gkHGO9+Zt5Jxw==,type:str]
    SECRET_HASS_TOKEN: ENC[AES256_GCM,data:lWQ7EVkvx1ygxrm79XKshBisFzJYovGE23QyjurFCJRUQVWWY9ol+PZ3T4fEDdS7IMv7SVl8TMhQYQEMab1jQNxg9KJQ8UigbmGpQDUlDWPKSSMnWAJg+TYMRLliLG6z1wJbuavsZW3AAFc4BEjJcw5RMvR/g6i9zpT6MQ2w9ec4m+aqzOOz/50LTcC7DJds/mUIbxDWJW2GjIAD0yKd1W/G33ue3pWAkFPJCNTQvVdaWiIictzB,iv:4C8uYVVevC72XSf/Q9lEAjz+BHJxCSyIJJAEqkewCso=,tag:02l8BVAOTed3W2U7yjyNRw==,type:str]
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:ZaFa9JmJ6QzgQ93UXyb4ZSBy16m3s0WhgqPRtpYaq3Cu2RZDdw3I/cVkRm+k6GDShgXCpLnaNFL3vHltDx7q1pYaCbh7UPngk8lzrJqD/pKu,iv:BGdkr3k3t1YrbMz1HjQU+W3/NLY4eLA1/SOHVi7SoD0=,tag:JeeaqeCidqPg74GMCVJwDw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:X84NBA0zEpeLaPxZxdL7FA0DrGs=,iv:3SYCpjZHhjXlQJ2xPbKTwYfFSnB0uZvBg7YOywqmIN4=,tag:6kzDAhWAAVyXnc7AKE6xHg==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:13x9InJYmKYEaHl7bfTfGu1tpP37gMvHi2eXfplMpE9L1i3tQBJ5Ug==,iv:fxBKEdTsg84lstDb7h8XKT1LpXdSA/aTeqekbX8n93c=,tag:HAzhZc0DRxcea/t+/fsnhg==,type:str]
    SECRET_MINIO_ENDPOINT: ENC[AES256_GCM,data:XURP+R2SuczYWtHvQW87HA==,iv:8b1cROsX/HyDs0l+R9ltuU4YY3j2Ru3tuUmwjC6d0KE=,tag:PRfWlTO41ngrRcK4WS3nbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc2cyZjk4alJxR2twZGRK
            Nnp6TTdMTW9KUjBjSFRyRU1VWUh5cDl3U1VrCjhKV1g1WmdUZVBFMWM4MUcrVWNY
            bHphUTBiMFlvYVhlbklUWHVHNG1rVEkKLS0tIDlzcWdhVjBPQzlYTDVjUWg4YUtH
            TXA4L250TUtFYVhLcEhEc3BocHd5WmcKP/XlAdXCPAyxjakZvlMXVc71I88kJzET
            q0LHqylyKZqWVCJrOzHG4qSM4HZRaNqsUrCHIFLj7ktZkoUoLT29IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T19:21:49Z"
    mac: ENC[AES256_GCM,data:A0GpikYJzhmtQVbDTURHEjNtxoo0Udnz2Te5/O9i99/j3xetZQ5QUJ+v6EYIdlxHj1HEwa7KluLlVIbNn7muGQGqZ07U6XogQvaXnc5W4IkoeZJK2ue7phLzrkNXONSiNewidPJidtMdH4CMd3G4tFc8hg0oe9GnK8UXSXDxtDQ=,iv:VvLGWqq/iXuEdTtU3XKCDd0saQuD5N32fdpPKj9b4Mo=,tag:xApSi00xtVCHB1cAX8pHSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
