# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bsdmbot-token
    namespace: bots
stringData:
    TELEGRAM_API_KEY: ENC[AES256_GCM,data:RZv1hUEDGJnT7XI+UsjWm8L7A2mdu4uuDiWV+Ow34paZWEfmZL04lvmybSLixQ==,iv:dwDJa/HkE4aICWG4u1okKkLXIWSn96qwbm7XVcbo6d0=,tag:HlJNyxrRCDjObtT/y5wQww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3clQzY0E1UnZWV1VhMG5P
            cytLbUd6RjJla2VuSUF4akc2aVc0L1k1cVU0ClJVRlpWTVFyUkhtZ1p4cFU4YmRK
            bFdWMStkL3llQVUydlBsOHZ1b1YyNXcKLS0tIEZWRjE3SEw4UHRrcE1QRklaOFBY
            bE5SbmhvWmFOY2N4MDVBcVM4YklkS00Ku+suPCdBK5dJgKxm8E7et/PtHxlaiF7u
            wuaLHa+7i8IpuO0UqxHIET1VAfeNoODQDnFC3fZ0CP2V54sCtQpwuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-13T20:39:22Z"
    mac: ENC[AES256_GCM,data:XeuHP72wmanC04QiRYAvO3POTf6xTun9tnx+l3kY27EfUTqWiCg2slXezD0pitjWbPXSNfCVPJMSzUtJ8rTUPDTMwWEVTXQ3e44kxb+GzTDBGBDZOlKvCPiHzkwPwAXp6XtFgDCyG6+3NwDOJBuP7DsuxqwqscQaTyQ1h0n1Rxo=,iv:jMr90lIXprkcKMqnmYuXsl2YHxiHB9xZ41MmfeuzYgA=,tag:JuZC/iaZOu5vN9jptc4ORQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
