---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: reverse-proxy
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    generateTLS:
      enabled: true

    instances:
    - name: hass
      enabled: false
      test: false
      ip: 192.168.2.7
      port: 8123
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        tls:
        - hosts:
          - hass.${SECRET_DOMAIN}
        hosts:
        - host: hass.${SECRET_DOMAIN}
          path: /
        ingressClassName: "nginx"
    ingressPort:
      http: 80
      tls: 443
    
    connectionTest:
      waitretry: 2
      readtimeout: 2
      tries: 30
    
