---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: reverse-proxy
      version: 2.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    generateTLS:
      enabled: true

    instances:
    - name: hass
      enabled: true
      test: true
      ip: ${HOME_ASSISTANT_SERVER}
      port: 8123
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/target: "int.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        tls:
        - hosts:
          - hass.${SECRET_DOMAIN}
        hosts:
        - host: hass.${SECRET_DOMAIN}
          path: /
        ingressClassName: "internal"
      ingressClassName: "internal"
    ingressPort:
      http: 80
      tls: 443
    connectionTest:
      waitretry: 2
      readtimeout: 2
      tries: 30
    
