---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 10.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/unpoller
      tag: 2.1.3
    env:
      TZ: UTC
      UP_UNIFI_DEFAULT_URL: ${SECRET_UNIFI_HOST}
      UP_UNIFI_DEFAULT_USER: ${SECRET_UNIFI_USER}
      UP_UNIFI_DEFAULT_PASS: ${SECRET_UNIFI_PASSWORD}
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: true
      UP_PROMETHEUS_DISABLE: false
      UP_INFLUXDB_DISABLE: true
    
    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
      prometheusRule:
        enabled: true
