---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: ghcr.io/k8s-at-home/sabnzbd
      # -- image tag
      tag: v3.5.1
      # -- image pull policy
      pullPolicy: IfNotPresent
    env:
      TZ: "Europe/Berlin"
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
        - host: "sabnzbd.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sabnzbd.${SECRET_DOMAIN}"
        annotations: 
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "int.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "sabnzbd"
      api:
        enabled: true
        ingressClassName: "internal"
        hosts:
        - host: "sabnzbd.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "sabnzbd.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-v1
      shared:
        enabled: true
        type: emptyDir
        mountPath: /downloads/tmp
        existingClaim: sabnzbd-tmp
      downloads:
        enabled: true
        existingClaim: nfs-downloads-pvc
        mountPath: /downloads
    podSecurityContext:
      supplementalGroups:
      - 100
    resources:
      requests:
        memory: 500Mi
        cpu: 1000m
    nodeSelector:
        feature.node.kubernetes.io/storage-nonrotationaldisk: 'true'
